# kubernetes/airflow/airflow-values.yaml

# General Airflow Settings
defaultAirflowRepository: apache/airflow
defaultAirflowTag: 2.9.2 # Using Airflow 2.9.2
executor: KubernetesExecutor

# Webserver Configuration (for Airflow UI)
webserver:
  enabled: true
  service:
    type: NodePort
    ports:
      - name: web
        port: 8080
        targetPort: 8080
        nodePort: 30000

# Scheduler Configuration
scheduler:
  enabled: true

# PostgreSQL Database Configuration
postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow_password
    database: airflow
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: standard

# Redis Configuration (Disabled)
redis:
  enabled: false

# --- CRITICAL: GIT SYNC CONFIGURATION ---
gitSync:
  enabled: true # Enable the Git Sync sidecar
  repo: "https://github.com/tingyuliang0116/Multi-Model-Recommendation-System.git" # !!! REPLACE THIS WITH YOUR ACTUAL REPO URL (e.g., https://github.com/YourUsername/YourRepo.git) !!!
  branch: "main" # Or the branch where your DAGs are
  rev: "HEAD" # Pull the latest commit
  period: 10 # Sync every 10 seconds for quick updates
  subPath: "airflow/dags" # The path within your Git repo where your DAGs are located
  # For private repos, you'd add:
  # secret: airflow-git-secret # This would reference a Kubernetes Secret with your Git credentials

# --- IMPORTANT: DISABLE DAGS PERSISTENCE VIA HOSTPATH ---
# Git Sync will manage the DAGs volume itself, typically as an emptyDir or local PVC for each pod.
dags:
  persistence:
    enabled: false # VERY IMPORTANT: Disable this to prevent hostPath conflicts.
    # hostPath: "..." # Ensure this is commented out or removed
    # size: ...
    # accessMode: ...

# Logging Configuration
logs:
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: standard

# Extra Python Packages (Confirmed working via manual install)
extraPipPackages:
  - minio
  - pandas
  - s3fs
  - smart_open
  - fsspec # Explicitly include fsspec, it caused version conflicts earlier

# Triggerer configuration
triggerer:
  enabled: true
  replicas: 1

# StatsD
statsd:
  enabled: true