# Enable the webserver and scheduler
webserver:
  enabled: true
  service:
    type: NodePort
    ports:
      - name: web
        port: 8080
        targetPort: 8080
        nodePort: 30000 # You can pick a different port if 30000 is in use

scheduler:
  enabled: true

# Use a simple PostgreSQL database for metadata
postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow_password
    database: airflow
  persistence:
    enabled: true
    size: 5Gi

# Disable Redis and Celery for simplicity in local setup
redis:
  enabled: false
executor: KubernetesExecutor

# *** ADD THESE LINES FOR EXTRA PYTHON PACKAGES ***
# These packages will be installed into the Airflow pods (webserver, scheduler, workers/tasks)
# ensuring your DAG code has access to them.
extraPipPackages:
  - minio==7.1.1 # Specify a version if you want, or just 'minio'
  - pandas==2.2.2 # Specify a version if you want, or just 'pandas'
# If you also need a specific version of requests or other packages that MinIO/Pandas
# might depend on, you can add them here.

# Allow local Dags folder mounting (if you want to manage DAGs directly on host)
dags:
  persistence:
    enabled: true
    size: 1Gi

# Configure logging to stay within the cluster
logs:
  persistence:
    enabled: true
    size: 10Gi

# Ensure this image is pulled correctly by Minikube
defaultAirflowRepository: apache/airflow
defaultAirflowTag: 2.9.2 # Use a specific, recent version