# 1. Namespace Definition
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
  labels:
    app: mlflow

---
# 2. MLflow Deployment Definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          command: ["mlflow"]
          args:
            [
              "server",
              "--host",
              "0.0.0.0",
              "--port",
              "5000",
              "--backend-store-uri",
              "sqlite:///mlruns.db",
              "--default-artifact-root",
              "s3://mlflow-artifacts",
            ]
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "minioadmin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "minioadmin"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio-service.minio:9000"
          ports:
            - containerPort: 5000
              name: http
          volumeMounts:
            - name: mlflow-db-storage
              mountPath: "/mlruns.db-data"
      volumes:
        - name: mlflow-db-storage
          emptyDir: {}

---
# 3. MLflow Service Definition
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: mlflow
  labels:
    app: mlflow
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5000 # The port the service exposes within the cluster
      targetPort: 5000 # The port the mlflow container listens on
      name: http
  type: NodePort
