grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30005
  adminPassword: prom-admin-pass
  defaultDashboardsEnabled: true

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesPods: false
    podMonitorSelectorNilUsesPods: false
    additionalScrapeConfigs:
      - job_name: 'recommendation-services'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['recommendation-models']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "8000|8001|8002|8003"
            action: keep
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            regex: (.+)
            target_label: __metrics_path__
            replacement: "$1"
            action: replace
          - source_labels: [__address__]
            regex: "(.+)"
            target_label: __metrics_path__
            replacement: "/metrics"
            action: replace
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: "(.+)"
            target_label: app_name
            replacement: "$1"
            action: replace
          - source_labels: [__meta_kubernetes_pod_label_model]
            regex: "(.+)"
            target_label: model_type
            replacement: "$1"
            action: replace

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true