fullnameOverride: "rabbitmq"

auth:
  username: user
  password: password

persistence:
  enabled: true
  size: 5Gi
  storageClassName: standard

metrics:
  enabled: true

rabbitmq:
  managementPlugin:
    enabled: true

service:
  type: NodePort
  ports:
    amqp:
      nodePort: 30006
    http:
      nodePort: 30007